### PR TITLE
Readme tweaks

### PR DESCRIPTION
**Pull request by digitarald**
Sorry for taking a broader rewrite. Tried to shorten the paragraphs and make sure to highlight all the other places in case users get lost here.

### CODE REVIEW

**Review by olguzzar — APPROVED** [review]
These are great additions! I think it's good to go, but I'll wait until the end of the day to merge it in, in case @burkeholland has other thoughts

**Comment by Austindgk232** [comment]
#1

**Review by kbackpeople-jpg — COMMENTED** [review]
README.md

**Review by kbackpeople-jpg — COMMENTED** [review]
> digitarald/readme

**Pull request merged**
